services:
  - type: static
    name: tasmel-moris-frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    envVars:
      - key: NODE_VERSION
        value: "20"
      - key: VITE_API_BASE_URL
        value: "https://tasmel-moris-backend.onrender.com"
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
